package com.neerveda.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 🚨 Alert Model
 *
 * Represents an alert generated by the system when:
 * 1. Water quality parameters exceed safe limits
 * 2. Multiple symptom reports come from same village (outbreak risk)
 * 3. AI/ML model predicts high disease risk
 *
 * Alerts are sent via:
 * - SMS (Twilio)
 * - App notification
 * - Dashboard warning
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Alert {

    private String id;

    // Alert type
    private AlertType alertType;  // WATER_QUALITY, DISEASE_OUTBREAK, SYSTEM

    // Severity level
    private AlertSeverity severity;  // LOW, MEDIUM, HIGH, CRITICAL

    // Location
    private String villageId;
    private String villageName;
    private String district;
    private String state;
    private double latitude;
    private double longitude;

    // Alert details
    private String title;
    private String message;
    private String affectedParameter;  // e.g., "Turbidity", "pH"
    private double currentValue;       // The actual sensor reading
    private double thresholdValue;     // The safe limit

    // Status
    private String status;  // ACTIVE, ACKNOWLEDGED, RESOLVED

    // Timestamps
    private LocalDateTime createdAt;
    private LocalDateTime resolvedAt;

    // Who resolved it
    private String resolvedBy;

    public enum AlertType {
        WATER_QUALITY,      // IoT sensor reading exceeded threshold
        DISEASE_OUTBREAK,   // Multiple symptom reports from same area
        SYSTEM              // System/device issue
    }

    public enum AlertSeverity {
        LOW,       // Single parameter slightly above threshold
        MEDIUM,    // Parameter significantly above threshold
        HIGH,      // Multiple parameters exceeded / multiple reports
        CRITICAL   // Immediate action required
    }
}
